### ISSUE TITLE
[bug] Unable to serialize the VGG19 script module from NeuralStyleTransfer to a file

### ISSUE THREAD

**Issue by arrufat** [prabhuomkar/pytorch-cpp#47]
**To Reproduce**

Run:
```
python model/create_vgg19_layers_scriptmodule.py 
Traceback (most recent call last):
  File "model/create_vgg19_layers_scriptmodule.py", line 19, in <module>
    main()
  File "model/create_vgg19_layers_scriptmodule.py", line 14, in main
    vgg_19_layers.save(filename)
  File "/usr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 575, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Sequential' object has no attribute 'save'
```
**Expected behavior**
The script module should be generated.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Libtorch Version 1.4.1 (from Arch Linux repository)

**Comment by mfl28** [comment]
Thanks for reporting this bug! Fix is coming.
